// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolymarketWatchlist.Data;

#nullable disable

namespace PolymarketWatchlist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolymarketWatchlist.Models.FlagState", b =>
                {
                    b.Property<int>("WatchlistMarketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("bit");

                    b.HasKey("WatchlistMarketId");

                    b.ToTable("FlagState", (string)null);
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.LatestPrice", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MidPrice")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TokenId");

                    b.ToTable("LatestPrice", (string)null);
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HighThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("LowThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("WatchlistMarketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistMarketId");

                    b.ToTable("Rule", (string)null);
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Watchlist", (string)null);
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.WatchlistMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoPriceTokenId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoTokenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("int");

                    b.Property<string>("YesPriceTokenId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YesTokenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NoPriceTokenId");

                    b.HasIndex("WatchlistId");

                    b.HasIndex("YesPriceTokenId");

                    b.ToTable("WatchlistMarket", (string)null);
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.FlagState", b =>
                {
                    b.HasOne("PolymarketWatchlist.Models.WatchlistMarket", "WatchlistMarket")
                        .WithOne("FlagState")
                        .HasForeignKey("PolymarketWatchlist.Models.FlagState", "WatchlistMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchlistMarket");
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.Rule", b =>
                {
                    b.HasOne("PolymarketWatchlist.Models.WatchlistMarket", "WatchlistMarket")
                        .WithMany("Rules")
                        .HasForeignKey("WatchlistMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchlistMarket");
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.WatchlistMarket", b =>
                {
                    b.HasOne("PolymarketWatchlist.Models.LatestPrice", "NoPrice")
                        .WithMany()
                        .HasForeignKey("NoPriceTokenId");

                    b.HasOne("PolymarketWatchlist.Models.Watchlist", "Watchlist")
                        .WithMany("Markets")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolymarketWatchlist.Models.LatestPrice", "YesPrice")
                        .WithMany()
                        .HasForeignKey("YesPriceTokenId");

                    b.Navigation("NoPrice");

                    b.Navigation("Watchlist");

                    b.Navigation("YesPrice");
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.Watchlist", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("PolymarketWatchlist.Models.WatchlistMarket", b =>
                {
                    b.Navigation("FlagState");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
